all:
	gcc -o crc16.exe crc16.c
	gcc -o crc16t.exe crc16t.c
	gcc -o crc32.exe crc32.c
	gcc -o crc32t.exe crc32t.c
	./crc16.exe
	./crc16t.exe
	./crc32.exe
	./crc32t.exe
	make clean

clean:
	rm crc16.exe
	rm crc16t.exe
	rm crc32.exe
	rm crc32t.exe
